require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ImportTablesController do

  # This should return the minimal set of attributes required to create a valid
  # ImportTable. As you add validations to ImportTable, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ImportTablesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all import_tables as @import_tables" do
      import_table = ImportTable.create! valid_attributes
      get :index, {}, valid_session
      assigns(:import_tables).should eq([import_table])
    end
  end

  describe "GET show" do
    it "assigns the requested import_table as @import_table" do
      import_table = ImportTable.create! valid_attributes
      get :show, {:id => import_table.to_param}, valid_session
      assigns(:import_table).should eq(import_table)
    end
  end

  describe "GET new" do
    it "assigns a new import_table as @import_table" do
      get :new, {}, valid_session
      assigns(:import_table).should be_a_new(ImportTable)
    end
  end

  describe "GET edit" do
    it "assigns the requested import_table as @import_table" do
      import_table = ImportTable.create! valid_attributes
      get :edit, {:id => import_table.to_param}, valid_session
      assigns(:import_table).should eq(import_table)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ImportTable" do
        expect {
          post :create, {:import_table => valid_attributes}, valid_session
        }.to change(ImportTable, :count).by(1)
      end

      it "assigns a newly created import_table as @import_table" do
        post :create, {:import_table => valid_attributes}, valid_session
        assigns(:import_table).should be_a(ImportTable)
        assigns(:import_table).should be_persisted
      end

      it "redirects to the created import_table" do
        post :create, {:import_table => valid_attributes}, valid_session
        response.should redirect_to(ImportTable.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved import_table as @import_table" do
        # Trigger the behavior that occurs when invalid params are submitted
        ImportTable.any_instance.stub(:save).and_return(false)
        post :create, {:import_table => {}}, valid_session
        assigns(:import_table).should be_a_new(ImportTable)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ImportTable.any_instance.stub(:save).and_return(false)
        post :create, {:import_table => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested import_table" do
        import_table = ImportTable.create! valid_attributes
        # Assuming there are no other import_tables in the database, this
        # specifies that the ImportTable created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ImportTable.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => import_table.to_param, :import_table => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested import_table as @import_table" do
        import_table = ImportTable.create! valid_attributes
        put :update, {:id => import_table.to_param, :import_table => valid_attributes}, valid_session
        assigns(:import_table).should eq(import_table)
      end

      it "redirects to the import_table" do
        import_table = ImportTable.create! valid_attributes
        put :update, {:id => import_table.to_param, :import_table => valid_attributes}, valid_session
        response.should redirect_to(import_table)
      end
    end

    describe "with invalid params" do
      it "assigns the import_table as @import_table" do
        import_table = ImportTable.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ImportTable.any_instance.stub(:save).and_return(false)
        put :update, {:id => import_table.to_param, :import_table => {}}, valid_session
        assigns(:import_table).should eq(import_table)
      end

      it "re-renders the 'edit' template" do
        import_table = ImportTable.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ImportTable.any_instance.stub(:save).and_return(false)
        put :update, {:id => import_table.to_param, :import_table => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested import_table" do
      import_table = ImportTable.create! valid_attributes
      expect {
        delete :destroy, {:id => import_table.to_param}, valid_session
      }.to change(ImportTable, :count).by(-1)
    end

    it "redirects to the import_tables list" do
      import_table = ImportTable.create! valid_attributes
      delete :destroy, {:id => import_table.to_param}, valid_session
      response.should redirect_to(import_tables_url)
    end
  end

end
